#!/bin/bash
#
# Script for generating US English lesson content for Typing Turtle.
# Author: Wade Brainerd <wadetb@gmail.com>
#
# Typing Turtle content is generated using the 'lessonbuilder.py' program
# which comes in the TypingTurtle.activity directory.  This program
# can generate different kinds of lessons using a word list file.
# 
# You must supply a word list for your language.  It can be a plain
# text dictionary, the text of a public domain novel, etc.  You can
# concatenate several sources together into one word list.  It's 
# important to supply a good word list that will include all the 
# letters in your language, plus variations like capitals and punctuation.
#
# To create lesson content for a new language, copy this directory:
# TypingTurtle.activity/lessons/en_US/
#
# to:
# TypingTurtle.activity/lessons/xx_YY/
#
# where xx is your language code and YY is your country code.
#
# Modify the commands in the MAKELESSONS file in the new directory
# to generate lesson content for your language, taking into account
# the particulars of your keyboard layout and language.
#
# For more information on the lessonbuilder.py program, run:
# ../../lessonbuilder.py --help
#

# Generate the introductory lesson.
../../lessonbuilder.py --intro-lesson \
    --title="Welcome" \
    --desc="Click Start Lesson to begin your typing adventure." \
    --bronze-wpm=0 --silver-wpm=0 --gold-wpm=0 \
    --bronze-acc=25 --silver-acc=50 --gold-acc=100 \
    --order=0 \
    --output=intro.lesson

# Generate the home, top and bottom row lessons.
../../lessonbuilder.py --key-lesson \
    --title="The Home Row" \
    --desc="This lesson teaches you the a, s, d, f, g, h, j, k and l keys \nin the middle of the keyboard.\nThese keys are called the Home Row." \
    --keys="asdfghjkl" \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=1 \
    --output=homerow.lesson
    
../../lessonbuilder.py --game-lesson \
    --title="Home Row Balloons" \
    --desc="Practice the home row keys in this exciting game!\nDon't let any balloons get by!" \
    --keys="asdfghjkl" \
    --game='balloon' \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=2 \
    --output=homerowgame.lesson
    
../../lessonbuilder.py --key-lesson \
    --title="The Top Row" \
    --desc="This lesson teaches you the q, w, e, r, t, y, u, i, o and p keys \non the top row of the keyboard." \
    --keys="qwertyuiop" --base-keys="asdfghjkl" \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=3 \
    --output=toprow.lesson

../../lessonbuilder.py --game-lesson \
    --title="Top Row Balloons" \
    --desc="Practice the top row keys in this exciting game!\nDon't let any balloons get by!" \
    --keys="qwertyuiop" --base-keys="asdfghjkl" \
    --game='balloon' \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=4 \
    --output=toprowgame.lesson
    
../../lessonbuilder.py --key-lesson \
    --title="The Bottom Row" \
    --desc="This lesson teaches you the z, x, c, v, b, n and m keys \non the bottom row of the keyboard." \
    --keys="zxcvbnm" --base-keys="asdfghjklqwertyuiop" \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=5 \
    --output=bottomrow.lesson

../../lessonbuilder.py --game-lesson \
    --title="Bottom Row Balloons" \
    --desc="Practice the bottom row keys in this exciting game!\nDon't let any balloons get by!" \
    --keys="zxcvbnm" --base-keys="asdfghjklqwertyuiop" \
    --game='balloon' \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=6 \
    --output=bottomrowgame.lesson
    
# Generate left and right hand capital lessons.
../../lessonbuilder.py --key-lesson \
    --title="Left Hand Capitals" \
    --desc="This lesson teaches you the CAPITAL letters which are typed \nby your left hand.\nThese are Q, W, E, R, T, A, S, D, F, G, Z, X, C, V and B." \
    --keys="QWERTASDFGZXCVB" --base-keys="abcdefghijklmnopqrstuvwxyz" \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=7 \
    --output=leftcapital.lesson

../../lessonbuilder.py --game-lesson \
    --title="Left Hand Capital Balloons" \
    --desc="Practice the left hand CAPITAL letters!\nDon't let any balloons get by!" \
    --keys="QWERTASDFGZXCVB" --base-keys="abcdefghijklmnopqrstuvwxyz" \
    --game='balloon' \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=8 \
    --output=leftcapitalgame.lesson
    
../../lessonbuilder.py --key-lesson \
    --title="Right Hand Capitals" \
    --desc="This lesson teaches you the CAPITAL letters which are typed \nby your right hand.\nThese are Y, U, I, O, P, H, J, K, L, N, and M." \
    --keys="YUIOPHJKLNM" --base-keys="abcdefghijklmnopqrstuvwxyzQWERTASDFGZXCVB" \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=9 \
    --output=rightcapital.lesson

../../lessonbuilder.py --game-lesson \
    --title="Right Hand Capital Balloons" \
    --desc="Practice the right hand CAPITAL letters!\nDon't let any balloons get by!" \
    --keys="YUIOPHJKLNM" --base-keys="abcdefghijklmnopqrstuvwxyzQWERTASDFGZXCVB" \
    --game='balloon' \
    --wordlist=5desk.txt --badwordlist=badwords.txt \
    --order=10 \
    --output=rightcapitalgame.lesson
    
