#!/bin/bash
#
# Script for generating en_US lesson content for Typing Turtle.
#

# Generate the introductory lesson.
../../lessonbuilder --make-intro-lesson --order=0 --output=intro.lesson

# Generate the home, top and bottom row lessons.
../../lessonbuilder --make-key-lesson \
    --title="The Home Row" \
    --desc="This lesson teaches you the ब, क, म, ा, न, ज, व, प and ि keys \nin the middle of the keyboard.\nThese keys are called the Home Row." \
    --keys="बकमाजवपि" \
    --wordlist=ne_NP.dic \
    --order=1 \
    --output=homerow.lesson
    
../../lessonbuilder --make-key-lesson \
    --title="The Top Row" \
    --desc="This lesson teaches you the त्र, ध, भ, च, त, थ, ग, ष, य and उ keys \non the top row of the keyboard." \
    --keys="त्रधभचतथगषयउ" --base-keys="बकमानजवपि" \
    --wordlist=ne_NP.dic \
    --order=2 \
    --output=toprow.lesson

../../lessonbuilder --make-key-lesson \
    --title="The Bottom Row" \
    --desc="This lesson teaches you the श, ह, अ, ख, द, ल and ः keys \non the bottom row of the keyboard." \
    --keys="शहअखदःः" --base-keys="बकमानजवपित्रधभचतथगषयउ" \
    --wordlist=ne_NP.dic \
    --order=3 \
    --output=bottomrow.lesson

# Generate left and right hand capital lessons.
../../lessonbuilder --make-key-lesson \
    --title="Left Hand Capitals" \
    --desc="This lesson teaches you the SECONDARY letters which are typed by your left hand.\nThese are त्त, ड्ढ, ऐ, द्ब, ट्ट, आ, ङ्क, ङ्ग, ँ, द्द, क्क, ह्य, ऋ, ॐ and ौ." \
    --keys="त्तड्ढऐद्बट्टआङ्कङ्गँद्दक्कह्यऋॐौ" \
    --base-keys="बदअमभानजषवपिःलयउत्रचकतगखधहथश"
    --wordlist=ne_NP.dic \
    --order=4 \
    --output=leftcapital.lesson

../../lessonbuilder --make-key-lesson \
    --title="Right Hand Capitals" \
    --desc="This lesson teaches you the CAPITAL letters which are typed by your right hand.\nThese are ठ्ठ, ऊ, क्ष, इ, ए, झ, ो, फ, ी, ौ, द्य, and ड्ड." \
    --keys="ठ्ठऊक्षइएझोफीौद्यड्ड" \
    --base-keys="बदअमभानजषवपिःलयउत्रचकतगखधहथशत्तड्ढऐद्बट्टआङ्कङ्गँद्दक्कह्यऋॐौ" \
    --wordlist=ne_NP.dic \
    --order=5 \
    --output=rightcapital.lesson
